[package]
name = "infrastructure"
version = "1.0.0"
edition = "2021"

[dependencies]
async-trait = "0.1.61"
domain = { path = "../domain" }
hyper = { version = "0.14.23", features = ["full"] }
pulldown-cmark = { version = "0.9.1" }
reqwest = "0.11.16"
